version: "3"
services:
  streamlit:
    build: .
    command: "streamlit run streamlit_app.py"
    ports:
      - "8501:8501"
    volumes:
      - "./:/app"
      - "~/.comet.config:/root/.comet.config"
